### ISSUE TITLE
Banches sans rendez-vous

### ISSUE THREAD

**Issue by Vonkuro** [Remistln/GestionPatient#2]
Il y a deux branches nommés sansrdv et sansrdv2.
L'une d'elles a été merge avec develop, c'est normal ?
Y a-il encore du travail à faire sur la page sans rendez-vous ?
Si oui, y aura-t-il de nouveaux changement dans l'API ?
Si non, peut-on les supprimés pour rendre le repository plus propre ?

Merci d'avance

**Comment by Remistln** [comment]
Bonjour, 

Oui le merge est normal. 
Il ne reste plus que la redirection dans sans rendez-vous puis la page sera finie.
L'API aura néanmoins un changement pour améliorer les fixtures dans la base de données.

En espérant que cela répond à vos questions
